services:
  cca.events_cron.cron_dispatcher:
    class: ContaoCommunityAlliance\Contao\Events\Cron\CronDispatcher
    arguments:
      - '@event_dispatcher'
      - '@cca.translator.contao_translator'
    public: true
